apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: smgoapp
    app.kubernetes.io/component: smgoapp
    app.kubernetes.io/instance: smgoapp
    app.kubernetes.io/name: smgoapp
    app.kubernetes.io/part-of: smgoapp
  name: smgoapp
  namespace: gotest
spec:
  lookupPolicy:
    local: false
