apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pull-from-all-ns
  namespace: gotest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:authenticated
